language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "NDtM4Nzptvpw1+1/H65T3PjQyYeSAg0tT4Ax6LqojzLiFGWXPPUl/c7cUHJwGWoJoIWAJHsv/O8d0ksQPF2Y5IvfnXH4dzeuVXn16Iw6FX0bQoXL44S0lw3XcK7rp/ADcH3cFM5inEpom4qsXxlR88J/w+M4jSyj2JQ5AD5JabKlFhWrPsqolG00QZBLswd42CYnXxYvn92+GVL0Qcjn7g2stsBV+uu76MJtgM4fABBlnIB8ld6uPcSSvBVRBeFkyYbyMHg9Fzmqfh3RATU2Ax8DIqE4rWhjSaN8wM33v3Fxlaz5vrlPXsip7S9DJIHRNeUI4TiFkNqsSI9XMWyEm/lsLvDU9X+CS7T9kDF1+Sr/0S0wyj6S2YhLEY0VhRqZDxteEcnMHAOZvqfaI3URBa2OyFFQO8dxd1AejEaHLiX9f2ytxliQ3MZv7213J0VrrK8SqnhCVYat93XwYgBJalofRcJxyE464cn/3sZidnCCLn4O/Z7LIsmwNno8OW5M7VJgk0U3FfYIv0UawLRJwewTx01XJipx86qejrYJJTOSmc3pYXZX07e+vf37NQf1Y5nMfzuQnEx7Pa9aYgfpiVbbAjFjwtugYSgcHYtz8IF/HJlZTmqGFY/FDEoG/GzrD5sokSnYkhEH3dw9rluuNZOKcA37rbb2/J1xT8Rz0Ng="
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: "michalperlak/gclipse"
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew test"
    branch_pattern: coverity-scan