language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "gi5FiXJQoJD3J+0T/i+rIsvUM9hoEFfLEklquSdoTbnaI9JPEyzzAJDIrYhBBwDeO4YM6HyqGfiOOx9nP1jlVg7Op6IMQ72zHkdf61BxMKDaEckHfWdZETfVc0+PsAQAF8wYvfbT1yD2r1ibG6PbX3LqSwgGAwmGqZKFERiKvKtUmbwQgJ8bG19ExVE/EDql/i7VJRIxuNz6ulCHBrgNMQdJ1HzW6BQ0xQotYq3d/CczeRHr9xIjfdBWuqw0QqrNUQMPEQqcP/2108rZ/lrENGIF5OdGhYWSNqi49gsLrXKipRR7pSy4Rj1j3qfCSqhNVPQCWFfplmz9bxepXgl7pMkom2aP8b/xypIHrVA2pFSgGcfbEtbsEt8fSzsUTgOPIH6YjQpeT0j7cr0GRGS1WgHefXgLV7a+bSVl6sF8g0b/fOotfgjgOpPJ9zIL1tQg1dGq4oWNXGPDMKtr0PPuW6/ZndHNV7+gNFrCv4mOW+HqblCxNJyUx692dZUINvvEmaBMDfL526uaOQRmIJeQibGW7E2MNgpTnsDCaa1xKuOpDKfHPjjM89rEJTsn8mqEOz5UMg062J8PkKDDAyL7/Z/fxjvyIJXmI5eAv6LOgL4lNAVflrTRovx5ZyW6KWaRUttBidWxIsfxP0u7Q/P7yXei5DOGY98yVTZ+aaV5DwI="
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: "michalperlak/gclipse"
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew test"